name: CI
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Integration Test
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 #v2.7.0
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 #v1.7.0

      - name: Cache Docker layer
        uses: actions/cache@2b250bc32ad02700b996b496c14ac8c2840a2991 #v2.1.8
        with:
            path: /tmp/.buildx-cache
            key: ${{ runner.os }}-buildx-${{ github.sha }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 #v1.7.0
        with:
         role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
         role-duration-seconds: 1200
         aws-region: us-east-1

      - name: Login to ECR
        uses: docker/login-action@dd4fa0671be5250ee6f50aedf4cb05514abda2c7 #v1.14.1
        with:
          registry: public.ecr.aws

      - name: Build docker image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a #v2.10.0
        with:
          context: sampleapp
          push: true
          tags: |
            public.ecr.aws/u0d6r4y4/aws-otel-go-test-gorilla:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Run test containers
        run: docker-compose up --abort-on-container-exit
        working-directory: .github/collector
        env:
          LISTEN_ADDRESS: 0.0.0.0:8080
          APP_IMAGE: public.ecr.aws/u0d6r4y4/aws-otel-go-test-gorilla:${{ github.sha }}
          VALIDATOR_COMMAND: -c go-otel-trace-validation.yml --endpoint http://app:8080 -t ${{ github.run_id }}-${{ github.run_number }}
