name: PR Build for AWS OTel Go Modules

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.64

jobs:
  detect-modules-to-lint-and-test:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - id: set-modules
        run: |
          echo "modules=$(find . -name go.mod -d -not -path "./sample-apps/*" -not -path "./sampleapp/*" | sed -r 's|/[^/]+$||' | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_OUTPUT

  golangci-lint:
    needs: detect-modules-to-lint-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        modules: ${{ fromJSON(needs.detect-modules-to-lint-and-test.outputs.modules) }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: golangci-lint ${{ matrix.modules }}
        uses: golangci/golangci-lint-action@v6
        with:
          version: ${{ env.GOLANGCI_LINT_VERSION }}
          working-directory: ${{ matrix.modules }}

  test:
    needs: detect-modules-to-lint-and-test
    strategy:
      matrix:
        module: ${{ fromJSON(needs.detect-modules-to-lint-and-test.outputs.modules) }}
        go-version: ["1.24.0", "1.23.0", "~1.22.4"]
        platform:
          - os: ubuntu-latest
            arch: amd64
          - os: macos-13
            arch: amd64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: amd64
    runs-on: ${{ matrix.platform.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        check-latest: true

    - name: Run tests for Module with Coverage
      if: matrix.platform.os == 'windows-latest'
      working-directory: ${{ matrix.module }}
      env:
        GOARCH: ${{ matrix.platform.arch }}
      run: |
        go test -cover -race ./...

    - name: Run tests for Module and Generate Detailed Coverage Report
      if: matrix.platform.os != 'windows-latest'
      working-directory: ${{ matrix.module }}
      env:
        GOARCH: ${{ matrix.platform.arch }}
      run: |
        go test -coverprofile=coverage.out -race ./...
        go tool cover -func=coverage.out
        go tool cover -html=coverage.out -o coverage.html