name: PR Build

on:
  pull_request:
    branches:
      - main
      - prbuild

env:
  IMAGE_NAME: aws-otel-go-sampleapp
concurrency:
  group: pr-build-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.filter.outputs.changed }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          list-files: shell
          filters: .github/config/file-filters.yml

      - name: List all updated files
        run: |
          for file in ${{ steps.filter.outputs.all_files }}; do
            echo "$file"
          done

  build binary:
    runs-on: ubuntu-latest
    needs: changes
    steps:
    # Set up building environment, patch the dev repo code on dispatch events.  
    - name: Set up Go 1.x
      if: ${{ needs.changes.outputs.changed == 'true' }}
      uses: actions/setup-go@v2
      with:
        go-version: '^1.17.7'

    - name: Checkout
      if: ${{ needs.changes.outputs.changed == 'true' }}
      uses: actions/checkout@v2

    - name: Build Binary
      if: ${{ needs.changes.outputs.changed == 'true' }}
      working-directory: ./sampleapp
      run: go build
    
    - name: Build Image
      if: ${{ needs.changes.outputs.dockerfile == 'true' }}
      working-directory: ./sampleapp
      run: docker build -t sampleappimage .
